# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PaATUECu6z5z0_PZjK6U-VssUeuFlJSX
"""

pip install opencv-python

from google .colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("WIN_20240508_23_24_51_Pro.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google .colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("WIN_20240508_23_24_51_Pro.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google .colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("Screenshot (72).png")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google .colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("Screenshot (93).png")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)

from google .colab.patches import cv2_imshow
import cv2
rasm=cv2.imread("photo_2024-08-23_23-09-32.jpg")
cv2_imshow(rasm)

oqqora=cv2.cvtColor(rasm,cv2.COLOR_BGR2GRAY)
cv2_imshow(oqqora)